### ISSUE TITLE
error with keyring on raspberry

### ISSUE THREAD

**Issue by streanger** [streanger/abuseipdb-wrapper#11]
part of error message:
```python
(...)
secretstorage.exceptions.PromptDismissedException: Prompt dismissed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/bin/abuse", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/abuseipdb_wrapper/abuseipdb_wrapper.py", line 835, in main
    API_KEY = store_api_key()
              ^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/abuseipdb_wrapper/utils.py", line 72, in store_api_key
    API_KEY = keyring.get_password("abuse", username)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/keyring/core.py", line 56, in get_password
    return get_keyring().get_password(service_name, username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/keyring/backends/SecretService.py", line 78, in get_password
    collection = self.get_preferred_collection()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/keyring/backends/SecretService.py", line 63, in get_preferred_collection
    raise InitError(f"Failed to create the collection: {e}.") from e
keyring.errors.InitError: Failed to create the collection: Prompt dismissed..
```

---

as far as I understand it, problem is related directly to keyring, but it should be catched somehow on my side:
- https://forums.raspberrypi.com/viewtopic.php?t=310979
- https://github.com/Azure/azure-devops-cli-extension/issues/762

**Comment by streanger** [comment]
following command will prevent app (`abuse`) from crash, but now API_KEY won't be set at all (even using internal `key` command):
- `keyring --disable`
